---
title: "ENSC 480"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}

# Set upload to TRUE before uploading shinyapp

upload <- TRUE

if (upload == FALSE)
  
  {
  setwd("C:/Users/seile/Documents/queensu/teaching/classes/ENSC480/tutorials/ENSC480")
  .libPaths("C:/Users/seile/Documents/queensu/teaching/classes/ENSC480/tutorials/ENSC480/renv")
  }

library(learnr)
library(gradethis)
library(shiny)
library(latex2exp)
library(viridis)
library(magick)
library(pdftools)
library(latex2exp)
library(plantecophys)

gradethis::gradethis_setup()
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(exercise.timelimit = 60)
```

```{r child = 'LAI.Rmd'}
```

```{r child = 'programming.Rmd'}
```

```{r child = 'Ch02.Rmd'}
```

```{r child = 'Ch03.Rmd'}
```

```{r child = 'Ch04.Rmd'}
```

```{r child = 'Ch05.Rmd'}
```

```{r child = 'Ch06.Rmd'}
```

```{r child = 'Ch07.Rmd'}
```

```{r child = 'Ch09.Rmd'}
```

```{r child = 'Ch10.Rmd'}
```

```{r child = 'Ch11.Rmd'}
```

```{r child = 'Ch13.Rmd'}
```
